# Generated by Django 5.0.14 on 2025-10-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='text',
            new_name='body',
        ),
    ]
