#name = input("Введите ваше имя: ")
#print("Привет", name)
#age = input(f"{name}, Сколько вам лет: ")
#num1 = float(input("Введите первое число: "))
#num2 = float(input("Введите второе число: "))
#print()
#print("Операции с числами:")
#print()
#print("сложение -", num1 + num2)
#print("вычитание -", num1 - num2)
#print("умножение -", num1 * num2)
#print("деление -", num1 // num2)
#P = int(input("Начальная сумма вклада :"))
#R = int(input("Процент по вкладу :"))
#T = int(input("Количество лет :"))
#print("Начисленные проценты :", (P * R * T) / 100)
#C = int(input("Введите температуру в градусах Цельсия:"))
#F = (9 / 5) * (C) + 32
#print(C, "градусов Цельсия равны", F, "градусам Фаренгейта")
#def say_hello():
#    print("Hello")
#say_hello()
#say_hello()
#say_hello()
#def say_hello():
#    print("Hello")
#def say_goodbye():
#    print("Good Bye")
#say_hello()
#say_goodbye()